# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2016 CERN.
#
# Invenio is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.


notifications:
  email: false

sudo: false

language: python

cache:
  - pip

env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release
  - REQUIREMENTS=devel

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[all]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: lnielsen
  password:
    secure: NKkEhbA1PBtNvbGffv+qz3h+A26TZE2joC+w6LqJoeLPrZ/jsZX7wacx5+1vjWdcQrxZ6oounZlWmu5JtWYRl+RT2VuRAATheVhfAgJ+HBjtR5VsICv0DN1A26UwNDZyJCpglSuo90hM5d9yRLGYJBDpUbZxshopQnEQv9xtLL2Mtr0EqAwUdGdpJtfQcRbS+DEMArK0sq7DpWxVBIMdrnRynGoDmRTiXR8KfAz07CJcyUEYA+3j1QfXFffqOAzhv21dlOQS9RwVWL0Phs32AI5gWcW2sjoOT64Ey8rpfzXXln6yh5YXgp6+ME5313AEKQq/NLYZY6PXEJJYHKH/PqrpfkGGlahlXuSQxE/hN6q5oV2iUrtk5UQPWRXLKXwCzw3PdyiHfjedvtSxfyEozsxLkPDBBuQnTAdInwwVYGG2fWPhxJiYptmRRRueGrrGYWHXLygfYiLD9C9hsbrzj9/TXFBwCiGnIr1a0SN5acU3JngtFv7Mly7PuPJSaRLwUvDjzT/HX+5/3jAevrsKLPETYcd3gG+S8B75C0wZC6Ga406KNLNxNpE7m8DEMFVanDZlHw5DOaL5dn/z+3uRP5KK3l4Rqg3Ml2ZBFCrFf4dRsle2SEGNbD1ZrVvCcg2MEhV0xW02u3AiKFyTqFe6CiXiAiOQkh13FTTa85wihS4=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: "2.7"
    condition: $REQUIREMENTS = release
